repositories:
- name: "mocaccino-micro"
  url: "https://get.mocaccino.org/mocaccino-micro"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-extra"
  url: "https://get.mocaccino.org/mocaccino-extra"
  github: "https://github.com/mocaccinoOS/mocaccino-extra"
- name: "mocaccino-portage-tree"
  url: "https://get.mocaccino.org/mocaccino-portage-tree"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "mocaccino-micro-stable"
  url: "https://get.mocaccino.org/mocaccino-micro-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-extra-stable"
  url: "https://get.mocaccino.org/mocaccino-extra-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-extra"
- name: "mocaccino-portage-tree-stable"
  url: "https://get.mocaccino.org/mocaccino-portage-tree-stable"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "luet-official"
  url: "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"
  github: "https://github.com/Luet-lab/luet-repo"
- name: "livecd"
  url: "https://raw.githubusercontent.com/Luet-lab/livecd-specs/gh-pages"
  github: "https://github.com/Luet-lab/livecd-specs"
- name: "kernel"
  url: "https://get.mocaccino.org/mocaccino-kernel"
  github: "https://github.com/mocaccinoOS/kernel-repo"